### ISSUE TITLE
Not compatible with Laravel 8.43

### ISSUE THREAD

**Issue by jwohlfert23** [lazychaser/laravel-nestedset#509] opened 2021-05-25 13:54 UTC
In BaseRelation.php line 121:
                                                                               
  Declaration of Kalnoy\Nestedset\BaseRelation::getRelationQuery(Illuminate\D  
  atabase\Eloquent\Builder $query, Illuminate\Database\Eloquent\Builder $pare  
  nt, $columns = Array) should be compatible with Illuminate\Database\Eloquen  
  t\Relations\Relation::getRelationQuery()

**Comment by darwin-focus** [comment] 2021-05-25 14:55
We have the same issue

**Comment by marcandreappel** [comment] 2021-05-25 15:35
Confirm the same issue

**Comment by DoubleTC** [comment] 2021-05-26 04:02
Confirm the same issue

**Comment by drjoju** [comment] 2021-05-26 07:19
Confirmed the issue!!

In Laravel 8.43 a new method is introduced in Illuminate\Database\Eloquent\Relations\Relation class.

```
    /**
     * Get the query builder that will contain the relationship constraints.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected function getRelationQuery()
    {
        return $this->query;
    }
```

This method conflicts with Kalnoy\Nestedset\BaseRelation class

```
/**
     * @param EloquentBuilder $query
     * @param EloquentBuilder $parent
     * @param array $columns
     *
     * @return mixed
     */
    public function getRelationQuery(
        EloquentBuilder $query, EloquentBuilder $parent,
        $columns = [ '*' ]
    ) {
        return $this->getRelationExistenceQuery($query, $parent, $columns);
    }
```


So rename or delete this method is needed to work.

**Comment by realtebo** [comment] 2021-05-26 08:08
We cloned to create a PR, but actually getRelationQuery() is UNUSED inside this package.

BUT this is a public method so there is the risk that it's used inside other packages depending from this. 

I suggest to rename the function in THIS package, bumping major version because of potential breaking change

Waiting to fix, please block laravel dependency to <=8.42.1

**Comment by realtebo** [comment] 2021-05-26 08:38
laravel framework developers won't change name to this new function. I am soory. I kindly asked to the team but they closed the issue with a "won't change it"

**Comment by stayallive** [comment] 2021-05-26 10:07
This method also looks like an alias for `getRelationExistenceQuery` since it's just calling that with the exact same parameters and docblock, so `getRelationQuery` can be safely dropped.

Although this is a BC it might be the best move, even without a major release since this will break at some point anyway. But a major release is also a good solution of course.

**Comment by it-can** [comment] 2021-05-26 12:06
@stayallive can you add a PR?

**Comment by Vusys** [comment] 2021-05-26 13:37
Until a proper fix is available, I'm patching it with [cweagans/composer-patches](https://github.com/cweagans/composer-patches).

Since the `getRelationQuery` method is not used internally and we're not using it in our project, I've simply commented it out.

Here's the patch file: https://gist.github.com/Vusys/e45a130d572ee76da1ab15cd3bd0226f

If you want to take this approach:

1. Install composer-patches: `composer require cweagans/composer-patches`
2. Download the patch linked above and put it in a patches directory in the root of your project.
3. Add the following to your composer.json file:

```json
"extra": {
    "patches": {
        "kalnoy/nestedset": {
            "Patches conflicting getRelationQuery method for >= Laravel 8.43": "./patches/nestedset.patch"
        }
    }
},
```

4. Run `composer install` and it will patch the problem out:

```
Removing package kalnoy/nestedset so that it can be re-installed and re-patched.
  - Removing kalnoy/nestedset (v5.0.3)
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 1 install, 0 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing kalnoy/nestedset (v5.0.3): Extracting archive
  - Applying patches for kalnoy/nestedset
    ./patches/nestedset.patch (Patches conflicting getRelationQuery method for >= Laravel 8.43)
```

**Comment by stayallive** [comment] 2021-05-26 13:58
PR is opened: #510.

~~Patch is a great idea in the meantime, as an alternative to patches you can temporarily use a fork (you don't have to use mine, by all means create your own!). Until it's merged and/or released you can switch back and/or remove the patches.~~

~~### To use a fork:~~

~~Add your (or my) repository to your `composer.json`:~~

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/stayallive/laravel-nestedset.git"
        }
    ],
```

~~And change the dependency to use a specific commit in a specific branch:~~

```diff
-   "kalnoy/nestedset": "^5.0",
+   "kalnoy/nestedset": "dev-master#97341697400fae3eaf1e32eafc2e1f34036bc5ff as 5.0",
```

~~(In this case it references this commit: https://github.com/stayallive/laravel-nestedset/commit/97341697400fae3eaf1e32eafc2e1f34036bc5ff.)~~

~~And run `composer update` to pull in the forked commit.~~

---

v6 is out now that you can use safely! 🥳

**Comment by lazychaser** [comment] 2021-05-28 07:25
You can now use v6

**Closed as completed by lazychaser** 2021-05-28 07:25 UTC

**Comment by stayallive** [comment] 2021-05-28 11:33
Thanks @lazychaser for the quick action, much appreciated! 💪

**Comment by realtebo** [comment] 2021-05-28 11:59
Thanks from my company, too

**Comment by deanzod** [comment] 2021-08-24 09:21
I'm still getting this in Laravel 8.50.0 and v6
